# Generated by Django 3.2.7 on 2021-11-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0003_alter_refreshtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
