# Generated by Django 3.2.7 on 2021-11-09 19:39

from django.db import migrations
import goals_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0004_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', goals_app.models.CustomUserManager()),
            ],
        ),
    ]
