# Generated by Django 3.2.9 on 2021-11-29 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import goals_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals_app', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='task',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='goals_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=goals_app.models.CapitalizedCharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='goals_app.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='reason',
            field=goals_app.models.CapitalizedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=goals_app.models.CapitalizedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(12, '')]),
        ),
    ]
